### ISSUE TITLE
Update website live?

### ISSUE THREAD

**Issue by ronnicek** [prgcont/prgcont.cz#8]
Hi,

I was checking the website and there is typo for github repo (on website: https://www.github.com/containers-prague) and also there is missing address to Slack :)

I was about to repair the adress, but in file here in repo is right address to at least github :)

**Comment by rwngwn** [comment]
It seems, the template is not regenerated, I'll fix it soon. Thanks for reporting!

**Comment by rwngwn** [comment]
it should be fixed now.
